- name : learning condn
  hosts: localhost
  become : yes
  tasks:
    - name : printing fruits
      ansible.builtin.debug:
      msg : fruits
      when: input = "fruits"

    - name : Printing veg
      ansible.builtin.debug:
        msg: veg
        when : input = "veg"
