- name : stroring the task output
  hosts: localhost
  tasks:
    - name: stroring the task output
      ansible.builtin.Shell: uptime
      register : output

    - name : printing the previpus stored output
      ansible.builtin.debug:
        msg: "{{output}}"