- name : learning to store previous task output
  hosts: localhost
  tasks:
    - name: storing the task output
      ansible.builtin.Shell: uptime
      register : output

    - name : printing the previous stored output
      ansible.builtin.debug:
        msg: "{{output}}"