- name : Demo on var
  hosts: localhost
  become: yes
  vars:
    URL_PlaY: Play level printing
  tasks:
    - name : tasks level printing
      ansible.builtin.debug:
        msg: URL_Task -{{URL_Task}}
      vars:
        URL_Task: Task level printing

    - name : Play level printing
      ansible.builtin.debug:
        msg: URL_PlaY - {{ URL_PlaY }}

  roles:
    - demo

# Play level variable can be accessed by all tasks and roles
# tasks level varaible can be accessed by only that particulat task
# role level variable can be acceseed by all demo roles

