- name : Demo on var
  hosts: localhost
  become: yes
  vars:
    URL_PlaY: Play level printing
  tasks:
    - name : tasks level printing
      ansible.builtin.debug:
        URL_Task: Task level printing
        msg: URL_Task -{{URL_Task}}

    - name : Play level printing
      ansible.builtin.debug:
        msg:URL_PlaY - {{ URL_PlaY }}

  roles:
    - demo

